import type { AppData } from "./types";

const daysFromNow = (days: number, hour = 18) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const STORAGE_KEY = "echelon-lms-demo-v6";

export function createSeedData(): AppData {
  return {
    currentUserId: null,
    users: [
      {
        id: "u-admin",
        name: "Echelon Admin",
        email: "admin@echelon.edu.gh",
        password: "admin123",
        role: "admin",
      },
      {
        id: "u-ama",
        name: "Ama Mensah",
        email: "ama@student.gh",
        password: "demo123",
        role: "student",
      },
      {
        id: "u-kwame",
        name: "Kwame Boateng",
        email: "kwame@student.gh",
        password: "demo123",
        role: "student",
      },
    ],
    courses: [
      {
        id: "c-fa1",
        code: "ICAG · FA1",
        title: "Financial Accounting",
        level: "Level 1",
        priceGhs: 1200,
        blurb:
          "Learn double-entry, ledgers, and trial balances for Level 1.",
        audience: "People starting ICAG Level 1.",
        outcomes: [
          "Record money in and out the right way",
          "Make a trial balance and spot common mistakes",
          "Read a simple balance sheet and profit report",
        ],
        moduleIds: ["m-fa1-1", "m-fa1-2", "m-fa1-3"],
      },
      {
        id: "c-tx2",
        code: "ICAG · TX",
        title: "Taxation",
        level: "Professional",
        priceGhs: 1800,
        blurb:
          "Learn personal and company tax for the ICAG paper.",
        audience: "People who study while they work.",
        outcomes: [
          "Work out personal and company tax with clear steps",
          "Handle common GRA points that lose marks",
          "Answer story-style questions in a calm order",
        ],
        moduleIds: ["m-tx-1", "m-tx-2", "m-tx-3"],
      },
      {
        id: "c-aa",
        code: "ICAG · AA",
        title: "Audit and Assurance",
        level: "Professional",
        priceGhs: 2000,
        blurb:
          "Learn audit risk, evidence, and reporting for the AA paper.",
        audience: "People taking Audit and Assurance.",
        outcomes: [
          "Match risks to the right audit steps",
          "Decide if the proof is strong enough",
          "Write a clear answer the marker can follow",
        ],
        moduleIds: ["m-aa-1", "m-aa-2", "m-aa-3"],
      },
      {
        id: "c-ma",
        code: "ICAG · MA",
        title: "Management Accounting",
        level: "Level 1",
        priceGhs: 1500,
        blurb: "Learn costing, budgets, and decision numbers for the MA paper.",
        audience: "People taking Management Accounting.",
        outcomes: [
          "Work out basic product costs with clear steps",
          "Build a simple budget and explain the gaps",
          "Use numbers to support a clear recommendation",
        ],
        moduleIds: ["m-ma-1", "m-ma-2", "m-ma-3"],
      },
    ],
    modules: [
      {
        id: "m-fa1-1",
        courseId: "c-fa1",
        order: 1,
        title: "The accounting equation in the exam",
        summary: "Assets, liabilities, and equity, and how ICAG asks about them.",
        materialId: "mat-fa1-1",
        quizId: "q-fa1-1",
      },
      {
        id: "m-fa1-2",
        courseId: "c-fa1",
        order: 2,
        title: "Journals, ledgers, and the trial balance",
        summary: "From source papers to a balanced trial balance.",
        materialId: "mat-fa1-2",
        quizId: "q-fa1-2",
      },
      {
        id: "m-fa1-3",
        courseId: "c-fa1",
        order: 3,
        title: "Reading the financial statements",
        summary: "How the books link to the main reports.",
        materialId: "mat-fa1-3",
      },
      {
        id: "m-tx-1",
        courseId: "c-tx2",
        order: 1,
        title: "Ghana tax rules and residency",
        summary: "Who pays tax, on what, and why where you live matters.",
        materialId: "mat-tx-1",
        quizId: "q-tx-1",
      },
      {
        id: "m-tx-2",
        courseId: "c-tx2",
        order: 2,
        title: "Pay and allowed deductions",
        summary: "Personal tax steps that hold up in the exam.",
        materialId: "mat-tx-2",
        quizId: "q-tx-2",
      },
      {
        id: "m-tx-3",
        courseId: "c-tx2",
        order: 3,
        title: "Company tax basics",
        summary: "From accounting profit to taxable profit.",
        materialId: "mat-tx-3",
      },
      {
        id: "m-aa-1",
        courseId: "c-aa",
        order: 1,
        title: "Ethics and engagement risk",
        summary: "Stay fair and careful before you start the work.",
        materialId: "mat-aa-1",
        quizId: "q-aa-1",
      },
      {
        id: "m-aa-2",
        courseId: "c-aa",
        order: 2,
        title: "Finding risk and how to respond",
        summary: "Match each risk to the right audit step.",
        materialId: "mat-aa-2",
        quizId: "q-aa-2",
      },
      {
        id: "m-aa-3",
        courseId: "c-aa",
        order: 3,
        title: "Proof, notes, and the report",
        summary: "What enough good proof looks like on paper.",
        materialId: "mat-aa-3",
      },
      {
        id: "m-ma-1",
        courseId: "c-ma",
        order: 1,
        title: "Costing basics",
        summary: "Direct cost, overhead, and how to build a unit cost.",
        materialId: "mat-ma-1",
        quizId: "q-ma-1",
      },
      {
        id: "m-ma-2",
        courseId: "c-ma",
        order: 2,
        title: "Budgets and variances",
        summary: "Plan the numbers, then explain why actuals differ.",
        materialId: "mat-ma-2",
        quizId: "q-ma-2",
      },
      {
        id: "m-ma-3",
        courseId: "c-ma",
        order: 3,
        title: "Decisions with numbers",
        summary: "Relevant cost for make, buy, and pricing choices.",
        materialId: "mat-ma-3",
      },
    ],
    materials: [
      {
        id: "mat-fa1-1",
        courseId: "c-fa1",
        title: "Session notes: The accounting equation",
        kind: "notes",
        minutes: 18,
        body: [
          "Every ICAG financial accounting paper begins with the same quiet truth: the accounting equation is not a definition to memorise. It is a control system.",
          "Assets = Liabilities + Equity. When a transaction arrives in the exam, ask first which side moves, and by how much. Marks are lost when candidates jump to journals before the equation is stable.",
          "Worked stance for Echelon candidates: state the equation impact in one line, then post. Examiners reward that discipline because it prevents the cascade errors that wipe entire workings.",
          "Ghana context tip: inventory purchases on credit, owner drawings, and bank overdrafts appear constantly in Level 1 scenarios. Treat overdrafts as liabilities unless the question states otherwise.",
          "Before you leave this module, you should be able to narrate any simple transactions effect on the equation without looking at a T-account.",
        ],
      },
      {
        id: "mat-fa1-2",
        courseId: "c-fa1",
        title: "Session notes: Journals to trial balance",
        kind: "notes",
        minutes: 22,
        body: [
          "Source document ? journal ? ledger ? trial balance. Miss a step and the TB will still balance while remaining wrong. That is the Level 1 trap.",
          "Echelon method: date, narration, debit, credit. Narrations are not decoration; they are how markers follow your logic when figures wobble under time pressure.",
          "Suspense accounts exist for a reason. If the TB fails, isolate. Do not rebuild the entire ledger in panic. Show the marker you can diagnose.",
          "Practice rule: every evening before a tutorial, post five transactions from memory. Speed without structure is noise; structure with speed is a pass.",
        ],
      },
      {
        id: "mat-fa1-3",
        courseId: "c-fa1",
        title: "Session notes: Reading the statements",
        kind: "notes",
        minutes: 16,
        body: [
          "The statement of financial position is a photograph; the statement of profit or loss is a film reel. Candidates confuse the two when they park drawings or capital incorrectly.",
          "Link every closing ledger balance to a line on the statements. If you cannot point to it, you are not finished.",
          "Exam presentation matters. Label clearly. Align workings. Leave a trail a tired marker can grade in seconds.",
        ],
      },
      {
        id: "mat-tx-1",
        courseId: "c-tx2",
        title: "Briefing: Ghana tax framework",
        kind: "notes",
        minutes: 20,
        body: [
          "Taxation papers punish vague language. Resident, year of assessment, and chargeable income each carry precise meaning under Ghanaian law as examined by ICAG.",
          "Start every question by classifying the taxpayer and the income streams. Mixing employment and business income without structure is how marks evaporate.",
          "Echelon stance: write the statutory hook in the margin of your workings, even a short phrase. It keeps you honest when the scenario turns messy.",
        ],
      },
      {
        id: "mat-tx-2",
        courseId: "c-tx2",
        title: "Briefing: Employment income",
        kind: "notes",
        minutes: 24,
        body: [
          "Cash is easy. Benefits in kind are where candidates stumble. Build a habit: list cash emoluments, then benefits, then deductions, always in that order.",
          "Allowable deductions must be earned by the legislation, not by sympathy. If you cannot defend it, do not claim it in the exam.",
          "Timed drill: complete one full PIT computation in 25 minutes. Then annotate every figure with its source line from the question.",
        ],
      },
      {
        id: "mat-tx-3",
        courseId: "c-tx2",
        title: "Briefing: Corporate tax bridge",
        kind: "notes",
        minutes: 20,
        body: [
          "Accounting profit is not taxable profit. The bridge (addbacks and deductions) is the entire game.",
          "Depreciation versus capital allowances, entertaining, and provisions appear repeatedly. Learn the pattern, not the panic.",
          "Show the bridge as a vertical working. Markers skim vertical bridges faster than prose paragraphs.",
        ],
      },
      {
        id: "mat-aa-1",
        courseId: "c-aa",
        title: "Briefing: Ethics & engagement risk",
        kind: "notes",
        minutes: 18,
        body: [
          "Before procedures, there is judgement. Threats to independence are not essay padding. They change the engagement response.",
          "Name the threat, evaluate significance, state the safeguard. That three-step rhythm is how AA answers earn professional marks.",
          "Scepticism is not cynicism. It is the refusal to accept managements story without evidence that could survive review.",
        ],
      },
      {
        id: "mat-aa-2",
        courseId: "c-aa",
        title: "Briefing: Risk to response",
        kind: "notes",
        minutes: 22,
        body: [
          "Identified risk without a linked procedure is an incomplete answer. Always close the loop: risk ? assertion ? procedure ? evidence expected.",
          "Use precise verbs: inspect, observe, recalculate, confirm. Soft verbs lose soft marks.",
          "In tutorials we will test your responses live. Arrive with one risk register drafted from the pre-reading.",
        ],
      },
      {
        id: "mat-aa-3",
        courseId: "c-aa",
        title: "Briefing: Evidence & reporting",
        kind: "notes",
        minutes: 16,
        body: [
          "Sufficient and appropriate are twin tests. Volume without relevance fails; relevance without volume also fails.",
          "Documentation is how your future self, and the reviewer, understands what you did. Write as if someone will challenge it.",
          "Reporting conclusions must match the evidence trail. Surprises in the final paragraph are a red flag for markers.",
        ],
      },
      {
        id: "mat-ma-1",
        courseId: "c-ma",
        title: "Session notes: Costing basics",
        kind: "notes",
        minutes: 18,
        body: [
          "Management accounting asks what a product or service really costs. Start with direct materials and direct labour. Then decide how to share overhead in a fair way.",
          "Echelon method: write your cost card in three clear lines. Markers follow neat cards faster than long stories.",
          "If overhead is absorbed, show the rate and the base. Do not hide the working. A wrong rate with a clear trail still earns method marks.",
        ],
      },
      {
        id: "mat-ma-2",
        courseId: "c-ma",
        title: "Session notes: Budgets and variances",
        kind: "notes",
        minutes: 20,
        body: [
          "A budget is a plan in numbers. A variance is the gap between plan and actual. Name the gap, then explain it in plain words.",
          "Favourable is not always good, and adverse is not always bad. Link each variance to a cause the manager can act on.",
          "In the exam, show the formula, the figures, and a one-line comment. That rhythm keeps you calm under time pressure.",
        ],
      },
      {
        id: "mat-ma-3",
        courseId: "c-ma",
        title: "Session notes: Decisions with numbers",
        kind: "notes",
        minutes: 16,
        body: [
          "Relevant cost means the cash that changes because of the decision. Ignore sunk costs. Ignore costs that stay the same either way.",
          "For make-or-buy and special orders, list the incremental inflows and outflows. End with a clear yes or no and one supporting reason.",
          "Presentation tip: put the recommendation first, then the workings. Markers should never hunt for your answer.",
        ],
      },
    ],
    quizzes: [
      {
        id: "q-fa1-1",
        courseId: "c-fa1",
        title: "Try-set · Accounting equation",
        questions: [
          {
            id: "qf11",
            prompt: "A sole trader buys inventory on credit. What is the immediate equation effect?",
            options: [
              "Assets up, equity up",
              "Assets up, liabilities up",
              "Assets down, liabilities down",
              "Liabilities up, equity down",
            ],
            answerIndex: 1,
          },
          {
            id: "qf12",
            prompt: "Owner drawings of cash primarily reduce which element?",
            options: ["Liabilities", "Assets and equity", "Only liabilities", "Revenue"],
            answerIndex: 1,
          },
          {
            id: "qf13",
            prompt: "A bank overdraft is best classified as:",
            options: ["A non-current asset", "Equity", "A liability", "Drawings"],
            answerIndex: 2,
          },
        ],
      },
      {
        id: "q-fa1-2",
        courseId: "c-fa1",
        title: "Try-set · Journals & TB",
        questions: [
          {
            id: "qf21",
            prompt: "A trial balance that balances always means the books are free of error.",
            options: ["True", "False"],
            answerIndex: 1,
          },
          {
            id: "qf22",
            prompt: "Which sequence is correct?",
            options: [
              "Ledger ? journal ? source document",
              "Source document ? journal ? ledger ? trial balance",
              "Trial balance ? journal ? ledger",
              "Journal ? trial balance ? source document",
            ],
            answerIndex: 1,
          },
        ],
      },
      {
        id: "q-tx-1",
        courseId: "c-tx2",
        title: "Try-set · Tax framework",
        questions: [
          {
            id: "qt11",
            prompt: "The first analytical step in a tax scenario is usually to:",
            options: [
              "Compute capital allowances",
              "Classify the taxpayer and income streams",
              "Draft the tax invoice",
              "Ignore residency",
            ],
            answerIndex: 1,
          },
          {
            id: "qt12",
            prompt: "Vague narrative without statutory hooks typically:",
            options: ["Earns method marks", "Loses marks under ICAG scrutiny", "Is preferred by markers", "Replaces workings"],
            answerIndex: 1,
          },
        ],
      },
      {
        id: "q-tx-2",
        courseId: "c-tx2",
        title: "Try-set · Employment income",
        questions: [
          {
            id: "qt21",
            prompt: "A disciplined PIT working order is:",
            options: [
              "Deductions ? benefits ? cash",
              "Cash emoluments ? benefits ? deductions",
              "Benefits only",
              "Tax payable first",
            ],
            answerIndex: 1,
          },
        ],
      },
      {
        id: "q-aa-1",
        courseId: "c-aa",
        title: "Try-set · Ethics",
        questions: [
          {
            id: "qa11",
            prompt: "The recommended ethics rhythm is:",
            options: [
              "Safeguard ? ignore threat",
              "Threat ? significance ? safeguard",
              "Opinion ? threat",
              "Procedure ? independence",
            ],
            answerIndex: 1,
          },
        ],
      },
      {
        id: "q-aa-2",
        courseId: "c-aa",
        title: "Try-set · Risk response",
        questions: [
          {
            id: "qa21",
            prompt: "A complete audit response links:",
            options: [
              "Risk only",
              "Risk ? assertion ? procedure ? evidence",
              "Procedure ? fee",
              "Opinion ? marketing",
            ],
            answerIndex: 1,
          },
        ],
      },
      {
        id: "q-ma-1",
        courseId: "c-ma",
        title: "Try-set · Costing basics",
        questions: [
          {
            id: "qm11",
            prompt: "Direct materials are best described as:",
            options: [
              "Overhead shared across all products",
              "Materials that can be traced to one product",
              "Sunk costs from last year",
              "Only delivery costs",
            ],
            answerIndex: 1,
          },
          {
            id: "qm12",
            prompt: "An overhead absorption rate should show:",
            options: [
              "Only the final unit cost",
              "The rate and the base used",
              "Profit before tax",
              "Residency status",
            ],
            answerIndex: 1,
          },
        ],
      },
      {
        id: "q-ma-2",
        courseId: "c-ma",
        title: "Try-set · Budgets",
        questions: [
          {
            id: "qm21",
            prompt: "A variance is:",
            options: [
              "The tax rate for the year",
              "The gap between budget and actual",
              "A type of audit evidence",
              "Owner drawings",
            ],
            answerIndex: 1,
          },
        ],
      },
    ],
    sessions: [
      {
        id: "s-call-1",
        title: "Call: which paper should I sit?",
        type: "call",
        courseId: null,
        startsAt: daysFromNow(2, 10),
        durationMin: 30,
        capacity: 1,
        mode: "Online",
        notes: "For people still choosing a paper.",
      },
      {
        id: "s-call-2",
        title: "Call: evening slot",
        type: "call",
        courseId: null,
        startsAt: daysFromNow(3, 19),
        durationMin: 30,
        capacity: 1,
        mode: "Online",
      },
      {
        id: "s-fa1-tut",
        title: "FA1 tutorial: accounting equation",
        type: "tutorial",
        courseId: "c-fa1",
        startsAt: daysFromNow(4, 18),
        durationMin: 90,
        capacity: 12,
        mode: "Online",
      },
      {
        id: "s-tx-tut",
        title: "TX tutorial: PIT workings",
        type: "tutorial",
        courseId: "c-tx2",
        startsAt: daysFromNow(5, 18),
        durationMin: 90,
        capacity: 10,
        mode: "Online",
      },
      {
        id: "s-aa-tut",
        title: "AA tutorial: risk register",
        type: "tutorial",
        courseId: "c-aa",
        startsAt: daysFromNow(6, 9),
        durationMin: 120,
        capacity: 8,
        mode: "Online",
      },
      {
        id: "s-ma-tut",
        title: "MA tutorial: costing basics",
        type: "tutorial",
        courseId: "c-ma",
        startsAt: daysFromNow(7, 18),
        durationMin: 90,
        capacity: 12,
        mode: "Online",
      },
      {
        id: "s-fa1-sat",
        title: "FA1 Saturday intensives",
        type: "tutorial",
        courseId: "c-fa1",
        startsAt: daysFromNow(8, 10),
        durationMin: 180,
        capacity: 15,
        mode: "Accra campus",
      },
    ],
    enrolments: [
      {
        id: "e-ama-fa1",
        userId: "u-ama",
        courseId: "c-fa1",
        enrolledAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
        completedModuleIds: ["m-fa1-1"],
        quizScores: { "q-fa1-1": 67 },
      },
      {
        id: "e-kwame-tx",
        userId: "u-kwame",
        courseId: "c-tx2",
        enrolledAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
        completedModuleIds: [],
        quizScores: {},
      },
    ],
    bookings: [
      {
        id: "b-ama-fa1",
        sessionId: "s-fa1-tut",
        userId: "u-ama",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      },
    ],
  };
}
